version: '3.8'

services:
  product-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped 